// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v2

import (
	context "context"
	time "time"

	apisciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/client/listers/cilium.io/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumClusterwideLocalRedirectPolicyInformer provides access to a shared informer and lister for
// CiliumClusterwideLocalRedirectPolicies. Prefer using the type-safe variant (see [TypedCiliumClusterwideLocalRedirectPolicyInformer]).
type CiliumClusterwideLocalRedirectPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ciliumiov2.CiliumClusterwideLocalRedirectPolicyLister
}

// TypedCiliumClusterwideLocalRedirectPolicyInformer provides access to a shared informer and lister for
// CiliumClusterwideLocalRedirectPolicies, including the type-safe TypedInformer variant.
// It is a superset of CiliumClusterwideLocalRedirectPolicyInformer.
type TypedCiliumClusterwideLocalRedirectPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CiliumClusterwideLocalRedirectPolicyIndexInformer
	Lister() ciliumiov2.CiliumClusterwideLocalRedirectPolicyLister
}

// CiliumClusterwideLocalRedirectPolicyIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CiliumClusterwideLocalRedirectPolicyIndexInformer cache.TypedSharedIndexInformer[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

// CiliumClusterwideLocalRedirectPolicyHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for CiliumClusterwideLocalRedirectPolicy.
type CiliumClusterwideLocalRedirectPolicyHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

// CiliumClusterwideLocalRedirectPolicyDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for CiliumClusterwideLocalRedirectPolicy.
type CiliumClusterwideLocalRedirectPolicyDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

// CiliumClusterwideLocalRedirectPolicyFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for CiliumClusterwideLocalRedirectPolicy.
type CiliumClusterwideLocalRedirectPolicyFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

// CiliumClusterwideLocalRedirectPolicyIndexers is a specialization of [cache.TypedIndexers] for CiliumClusterwideLocalRedirectPolicy.
type CiliumClusterwideLocalRedirectPolicyIndexers = cache.TypedIndexers[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

// DeletedCiliumClusterwideLocalRedirectPolicy is a specialization of [cache.DeletedObject] for CiliumClusterwideLocalRedirectPolicy.
type DeletedCiliumClusterwideLocalRedirectPolicy = cache.DeletedObject[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy]

type ciliumClusterwideLocalRedirectPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCiliumClusterwideLocalRedirectPolicyInformer constructs a new informer for CiliumClusterwideLocalRedirectPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumClusterwideLocalRedirectPolicyInformer]).
func NewCiliumClusterwideLocalRedirectPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCiliumClusterwideLocalRedirectPolicyInformer constructs a new informer for CiliumClusterwideLocalRedirectPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumClusterwideLocalRedirectPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumClusterwideLocalRedirectPolicyIndexers) CiliumClusterwideLocalRedirectPolicyIndexInformer {
	return NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCiliumClusterwideLocalRedirectPolicyInformer constructs a new informer for CiliumClusterwideLocalRedirectPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCiliumClusterwideLocalRedirectPolicyInformer]).
func NewFilteredCiliumClusterwideLocalRedirectPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCiliumClusterwideLocalRedirectPolicyInformer constructs a new informer for CiliumClusterwideLocalRedirectPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCiliumClusterwideLocalRedirectPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumClusterwideLocalRedirectPolicyIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CiliumClusterwideLocalRedirectPolicyIndexInformer {
	return NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCiliumClusterwideLocalRedirectPolicyInformerWithOptions constructs a new informer for CiliumClusterwideLocalRedirectPolicy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions]).
func NewCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, options)
}

// NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions constructs a new informer for CiliumClusterwideLocalRedirectPolicy type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) CiliumClusterwideLocalRedirectPolicyIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cilium.io", Version: "v2", Resource: "ciliumclusterwidelocalredirectpolicys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2().CiliumClusterwideLocalRedirectPolicies().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2().CiliumClusterwideLocalRedirectPolicies().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2().CiliumClusterwideLocalRedirectPolicies().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2().CiliumClusterwideLocalRedirectPolicies().Watch(ctx, opts)
			},
		}, client),
		&apisciliumiov2.CiliumClusterwideLocalRedirectPolicy{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *ciliumClusterwideLocalRedirectPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCiliumClusterwideLocalRedirectPolicyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *ciliumClusterwideLocalRedirectPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *ciliumClusterwideLocalRedirectPolicyInformer) TypedInformer() CiliumClusterwideLocalRedirectPolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy](f.factory.InformerFor(&apisciliumiov2.CiliumClusterwideLocalRedirectPolicy{}, f.defaultInformer))
}

func (f *ciliumClusterwideLocalRedirectPolicyInformer) Lister() ciliumiov2.CiliumClusterwideLocalRedirectPolicyLister {
	return ciliumiov2.NewCiliumClusterwideLocalRedirectPolicyLister(f.Informer().GetIndexer())
}

// ToTypedCiliumClusterwideLocalRedirectPolicyInformer converts an untyped informer into a TypedCiliumClusterwideLocalRedirectPolicyInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumClusterwideLocalRedirectPolicy. If that is not the case, calling type-safe methods of the returned
// TypedCiliumClusterwideLocalRedirectPolicyInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCiliumClusterwideLocalRedirectPolicyInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCiliumClusterwideLocalRedirectPolicyInformer(informer CiliumClusterwideLocalRedirectPolicyInformer) TypedCiliumClusterwideLocalRedirectPolicyInformer {
	if informer, ok := informer.(TypedCiliumClusterwideLocalRedirectPolicyInformer); ok {
		return informer
	}
	return &ciliumClusterwideLocalRedirectPolicyTypedInformerAdapter{informer}
}

type ciliumClusterwideLocalRedirectPolicyTypedInformerAdapter struct {
	CiliumClusterwideLocalRedirectPolicyInformer
}

func (a *ciliumClusterwideLocalRedirectPolicyTypedInformerAdapter) TypedInformer() CiliumClusterwideLocalRedirectPolicyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy](a.Informer())
}

// ToCiliumClusterwideLocalRedirectPolicyIndexInformer converts an untyped informer into a CiliumClusterwideLocalRedirectPolicyIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumClusterwideLocalRedirectPolicy. If that is not the case, calling type-safe methods of the returned
// CiliumClusterwideLocalRedirectPolicyIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CiliumClusterwideLocalRedirectPolicyIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCiliumClusterwideLocalRedirectPolicyIndexInformer(informer cache.SharedIndexInformer) CiliumClusterwideLocalRedirectPolicyIndexInformer {
	if informer, ok := informer.(CiliumClusterwideLocalRedirectPolicyIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2.CiliumClusterwideLocalRedirectPolicy](informer)
}
