// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumClusterwideLocalRedirectPolicies implements CiliumClusterwideLocalRedirectPolicyInterface
type fakeCiliumClusterwideLocalRedirectPolicies struct {
	*gentype.FakeClientWithList[*v2.CiliumClusterwideLocalRedirectPolicy, *v2.CiliumClusterwideLocalRedirectPolicyList]
	Fake *FakeCiliumV2
}

func newFakeCiliumClusterwideLocalRedirectPolicies(fake *FakeCiliumV2) ciliumiov2.CiliumClusterwideLocalRedirectPolicyInterface {
	return &fakeCiliumClusterwideLocalRedirectPolicies{
		gentype.NewFakeClientWithList[*v2.CiliumClusterwideLocalRedirectPolicy, *v2.CiliumClusterwideLocalRedirectPolicyList](
			fake.Fake,
			"",
			v2.SchemeGroupVersion.WithResource("ciliumclusterwidelocalredirectpolicies"),
			v2.SchemeGroupVersion.WithKind("CiliumClusterwideLocalRedirectPolicy"),
			func() *v2.CiliumClusterwideLocalRedirectPolicy { return &v2.CiliumClusterwideLocalRedirectPolicy{} },
			func() *v2.CiliumClusterwideLocalRedirectPolicyList {
				return &v2.CiliumClusterwideLocalRedirectPolicyList{}
			},
			func(dst, src *v2.CiliumClusterwideLocalRedirectPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v2.CiliumClusterwideLocalRedirectPolicyList) []*v2.CiliumClusterwideLocalRedirectPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2.CiliumClusterwideLocalRedirectPolicyList, items []*v2.CiliumClusterwideLocalRedirectPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
