// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumClusterwideLocalRedirectPoliciesGetter has a method to return a CiliumClusterwideLocalRedirectPolicyInterface.
// A group's client should implement this interface.
type CiliumClusterwideLocalRedirectPoliciesGetter interface {
	CiliumClusterwideLocalRedirectPolicies() CiliumClusterwideLocalRedirectPolicyInterface
}

// CiliumClusterwideLocalRedirectPolicyInterface has methods to work with CiliumClusterwideLocalRedirectPolicy resources.
type CiliumClusterwideLocalRedirectPolicyInterface interface {
	Create(ctx context.Context, ciliumClusterwideLocalRedirectPolicy *ciliumiov2.CiliumClusterwideLocalRedirectPolicy, opts v1.CreateOptions) (*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, error)
	Update(ctx context.Context, ciliumClusterwideLocalRedirectPolicy *ciliumiov2.CiliumClusterwideLocalRedirectPolicy, opts v1.UpdateOptions) (*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2.CiliumClusterwideLocalRedirectPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2.CiliumClusterwideLocalRedirectPolicy, err error)
	CiliumClusterwideLocalRedirectPolicyExpansion
}

// ciliumClusterwideLocalRedirectPolicies implements CiliumClusterwideLocalRedirectPolicyInterface
type ciliumClusterwideLocalRedirectPolicies struct {
	*gentype.ClientWithList[*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, *ciliumiov2.CiliumClusterwideLocalRedirectPolicyList]
}

// newCiliumClusterwideLocalRedirectPolicies returns a CiliumClusterwideLocalRedirectPolicies
func newCiliumClusterwideLocalRedirectPolicies(c *CiliumV2Client) *ciliumClusterwideLocalRedirectPolicies {
	return &ciliumClusterwideLocalRedirectPolicies{
		gentype.NewClientWithList[*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, *ciliumiov2.CiliumClusterwideLocalRedirectPolicyList](
			"ciliumclusterwidelocalredirectpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2.CiliumClusterwideLocalRedirectPolicy {
				return &ciliumiov2.CiliumClusterwideLocalRedirectPolicy{}
			},
			func() *ciliumiov2.CiliumClusterwideLocalRedirectPolicyList {
				return &ciliumiov2.CiliumClusterwideLocalRedirectPolicyList{}
			},
		),
	}
}
