// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2

import (
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumClusterwideLocalRedirectPolicyLister helps list CiliumClusterwideLocalRedirectPolicies.
// All objects returned here must be treated as read-only.
type CiliumClusterwideLocalRedirectPolicyLister interface {
	// List lists all CiliumClusterwideLocalRedirectPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, err error)
	// Get retrieves the CiliumClusterwideLocalRedirectPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2.CiliumClusterwideLocalRedirectPolicy, error)
	CiliumClusterwideLocalRedirectPolicyListerExpansion
}

// ciliumClusterwideLocalRedirectPolicyLister implements the CiliumClusterwideLocalRedirectPolicyLister interface.
type ciliumClusterwideLocalRedirectPolicyLister struct {
	listers.ResourceIndexer[*ciliumiov2.CiliumClusterwideLocalRedirectPolicy]
}

// NewCiliumClusterwideLocalRedirectPolicyLister returns a new CiliumClusterwideLocalRedirectPolicyLister.
func NewCiliumClusterwideLocalRedirectPolicyLister(indexer cache.Indexer) CiliumClusterwideLocalRedirectPolicyLister {
	return &ciliumClusterwideLocalRedirectPolicyLister{listers.New[*ciliumiov2.CiliumClusterwideLocalRedirectPolicy](indexer, ciliumiov2.Resource("ciliumclusterwidelocalredirectpolicy"))}
}
